### PR TITLE
Silent maps to not blink status message

### PR DESCRIPTION
**Pull request by thalesmello**
When using n to navigate to tbe next message, the status message was
blinking with part of the trailer command that is used to invoke the
callback function.

This commit makes it silent.

### CODE REVIEW

**Comment by junegunn** [comment]
I don't have the issue you're describing, no flashing status line. What am I missing?

**Comment by thalesmello** [comment]
@junegunn https://asciinema.org/a/LJ8ghu53ZLITyUUdkvbbxGql1

Please pay attention at the messages in the bottom of the screen.

It should the search `vim-slash` uses, which is a little distracting.

Adding the `<silent>` tags to the maps fixes this issue.

**Comment by junegunn** [comment]
Is it reproducible in regular Vim? I can't reproduce the flickering in Neovim or in Vim.

**Comment by thalesmello** [comment]
Yes. https://asciinema.org/a/ubnqKvLcuVOblAS1udKUxBbP5

I don't know if it helps, but I use:

- MacOS Sierra (version 10.12.5)
- tmux/HEAD-65d6278
- NVIM v0.2.1-648-gb765fba1a
- VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  6 2017 21:57:47)

Maps without `<silent>` are supposed to be printed in the command line. Maybe you have a `set` in your vimrc that disables that? Doing a quick google search showed me nothing.

Take a look at `:help :map-silent`.

**Comment by junegunn** [comment]
I've tested with an empty vimrc that has no settings and plugins at all but vim-slash. Have you tried that way? Anyway adding silent is not an issue, but I'd like to confirm that it's really needed before doing it.

**Comment by thalesmello** [comment]
Still happens.

https://asciinema.org/a/pRFG6P0SIeiJM14FloIlm6Leh

vimrc used in the test:

```
set runtimepath=/usr/local/Cellar/neovim/HEAD-eb40b7e_1/share/nvim/runtime

set runtimepath+=~/.vim/plugged/vim-slash
```

**Comment by thalesmello** [comment]
@junegunn I submitted the PR particularly because I noticed the status message behavior and I figured it could be useful to you, in case you haven't noticed it.

Since it actually doesn't affect you machine, it could be something with my setup, I don't know.

Feel free to close this PR. I'm going to use my fork, anyways.

**Comment by junegunn** [comment]
> Still happens.
> https://asciinema.org/a/pRFG6P0SIeiJM14FloIlm6Leh

Hmm, I don't see any flickering in that asciinema. Am I missing something?

**Comment by thalesmello** [comment]
Hum, my bad.

I tried Vim without any plugins, and noticed the default behavior is to actually print the search term in the status message. I thought it was the opposite, that it didn't print anything at all.

In my setup, because Vim is doing a lot of other things because of my other plugins, the cursor ends up flickering. Because of this, I find it better to have silent mappings.

This pull request is not necessary anymore.

**Pull request closed without merging**
